export const data = JSON.parse("{\"key\":\"v-476ae7b4\",\"path\":\"/md/projects/lottery.html\",\"title\":\"Lottery 抽奖系统\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Lottery 抽奖系统\",\"icon\":\"gift\",\"category\":[\"项目展示\",\"分布式系统\"],\"description\":\"项目概述 基于 DDD 领域驱动设计的分布式抽奖系统，支持多种抽奖策略和活动玩法。 技术架构 核心技术栈\\rSpring Boot 2.7+ - 微服务框架; \\rMyBatis 3.5+ - ORM 框架; \\rDubbo 3.0+ - RPC 框架; \\rRedis 6.0+ - 缓存和分布式锁; \\rMySQL 8.0+ - 主数据库; \\rRabbitMQ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/md/projects/lottery.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"我的简历\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Lottery 抽奖系统\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"项目概述 基于 DDD 领域驱动设计的分布式抽奖系统，支持多种抽奖策略和活动玩法。 技术架构 核心技术栈\\rSpring Boot 2.7+ - 微服务框架; \\rMyBatis 3.5+ - ORM 框架; \\rDubbo 3.0+ - RPC 框架; \\rRedis 6.0+ - 缓存和分布式锁; \\rMySQL 8.0+ - 主数据库; \\rRabbitMQ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"小傅哥\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Lottery 抽奖系统\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"小傅哥\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"项目概述\",\"slug\":\"项目概述\",\"link\":\"#项目概述\",\"children\":[]},{\"level\":2,\"title\":\"技术架构\",\"slug\":\"技术架构\",\"link\":\"#技术架构\",\"children\":[{\"level\":3,\"title\":\"核心技术栈\",\"slug\":\"核心技术栈\",\"link\":\"#核心技术栈\",\"children\":[]},{\"level\":3,\"title\":\"系统架构\",\"slug\":\"系统架构\",\"link\":\"#系统架构\",\"children\":[]}]},{\"level\":2,\"title\":\"核心功能\",\"slug\":\"核心功能\",\"link\":\"#核心功能\",\"children\":[{\"level\":3,\"title\":\"1. 抽奖引擎\",\"slug\":\"_1-抽奖引擎\",\"link\":\"#_1-抽奖引擎\",\"children\":[]},{\"level\":3,\"title\":\"2. 活动管理\",\"slug\":\"_2-活动管理\",\"link\":\"#_2-活动管理\",\"children\":[]},{\"level\":3,\"title\":\"3. 奖品发放\",\"slug\":\"_3-奖品发放\",\"link\":\"#_3-奖品发放\",\"children\":[]}]},{\"level\":2,\"title\":\"性能优化\",\"slug\":\"性能优化\",\"link\":\"#性能优化\",\"children\":[{\"level\":3,\"title\":\"1. 缓存策略\",\"slug\":\"_1-缓存策略\",\"link\":\"#_1-缓存策略\",\"children\":[]},{\"level\":3,\"title\":\"2. 数据库优化\",\"slug\":\"_2-数据库优化\",\"link\":\"#_2-数据库优化\",\"children\":[]},{\"level\":3,\"title\":\"3. 并发控制\",\"slug\":\"_3-并发控制\",\"link\":\"#_3-并发控制\",\"children\":[]}]},{\"level\":2,\"title\":\"项目亮点\",\"slug\":\"项目亮点\",\"link\":\"#项目亮点\",\"children\":[]}],\"readingTime\":{\"minutes\":1.17,\"words\":351},\"filePathRelative\":\"md/projects/lottery.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
