export const data = JSON.parse("{\"key\":\"v-184f4da6\",\"path\":\"/intro.html\",\"title\":\"关于我\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"关于我\",\"icon\":\"user\",\"order\":1,\"description\":\"你好，我是小傅哥 👋 欢迎来到我的技术博客！我是一名热爱技术的开发者，专注于 Java、Spring、Vue 等技术栈的学习和分享。 🚀 技术栈 后端: Java, Spring Boot, MyBatis, MySQL 前端: Vue.js, TypeScript, Element Plus 工具: Git, Docker, Nginx 其他: Redis, RabbitMQ, Elasticsearch\",\"head\":[[\"link\",{\"rel\":\"canonical\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/intro.html\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/intro.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"小傅哥的技术博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"关于我\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"你好，我是小傅哥 👋 欢迎来到我的技术博客！我是一名热爱技术的开发者，专注于 Java、Spring、Vue 等技术栈的学习和分享。 🚀 技术栈 后端: Java, Spring Boot, MyBatis, MySQL 前端: Vue.js, TypeScript, Element Plus 工具: Git, Docker, Nginx 其他: Redis, RabbitMQ, Elasticsearch\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"小傅哥\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"关于我\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"小傅哥\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"🚀 技术栈\",\"slug\":\"🚀-技术栈\",\"link\":\"#🚀-技术栈\",\"children\":[]},{\"level\":2,\"title\":\"📚 学习目标\",\"slug\":\"📚-学习目标\",\"link\":\"#📚-学习目标\",\"children\":[]},{\"level\":2,\"title\":\"🎯 联系方式\",\"slug\":\"🎯-联系方式\",\"link\":\"#🎯-联系方式\",\"children\":[]}],\"readingTime\":{\"minutes\":0.52,\"words\":157},\"filePathRelative\":\"intro.md\",\"excerpt\":\"<h1> 你好，我是小傅哥 👋</h1>\\n<p>欢迎来到我的技术博客！我是一名热爱技术的开发者，专注于 Java、Spring、Vue 等技术栈的学习和分享。</p>\\n<h2> 🚀 技术栈</h2>\\n<ul>\\n<li><strong>后端</strong>: Java, Spring Boot, MyBatis, MySQL</li>\\n<li><strong>前端</strong>: Vue.js, TypeScript, Element Plus</li>\\n<li><strong>工具</strong>: Git, Docker, Nginx</li>\\n<li><strong>其他</strong>: Redis, RabbitMQ, Elasticsearch</li>\\n</ul>\",\"copyright\":{\"author\":\"小傅哥\",\"license\":\"MIT\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
