export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Leo's Tech Lab","i":"home"},["/README.md"]],
  ["v-07cdea80","/about/career.html",{"y":"a","t":"我的成长路线"},[":md"]],
  ["v-45a132b4","/about/contact.html",{"y":"a","t":"联系方式"},[":md"]],
  ["v-74bc627b","/about/",{"y":"a","t":"关于我"},["/about/README.md"]],
  ["v-4da094c8","/about/skill-stack.html",{"y":"a","t":"技术栈"},[":md"]],
  ["v-1d52aa9d","/about/timeline.html",{"y":"a","t":"技术经历时间线"},[":md"]],
  ["v-9ce0695c","/architecture/architecture-thinking.html",{"y":"a","t":"架构思考"},[":md"]],
  ["v-71e0f828","/architecture/database-design.html",{"y":"a","t":"数据库设计"},[":md"]],
  ["v-5db2e59d","/architecture/distributed-system.html",{"y":"a","t":"分布式系统"},[":md"]],
  ["v-563f98f6","/architecture/microservice.html",{"y":"a","t":"微服务与系统演进"},[":md"]],
  ["v-63e82ae3","/architecture/",{"y":"a","t":"架构设计"},["/architecture/README.md"]],
  ["v-5c6e1940","/architecture/system-design.html",{"y":"a","t":"系统设计"},[":md"]],
  ["v-7b83ca2f","/growth/",{"y":"a","t":"成长记录"},["/growth/README.md"]],
  ["v-6dc367c8","/projects/",{"y":"a","t":"项目作品"},["/projects/README.md"]],
  ["v-230f97cc","/business-system/",{"y":"a","t":"业务系统实践"},["/business-system/README.md"]],
  ["v-1d59d0e6","/md/resume.html",{"y":"a","t":"个人简历","i":"laptop-code","I":0},[":md"]],
  ["v-2d0a776e","/ai/",{"y":"a","t":"AI 探索"},["/ai/README.md"]],
  ["v-15551100","/tech/",{"y":"a","t":"技术研究"},["/tech/README.md"]],
  ["v-02cb8be4","/troubleshooting/",{"y":"a","t":"经验沉淀"},["/troubleshooting/README.md"]],
  ["v-c8574498","/growth/books/",{"y":"a","t":"阅读记录"},["/growth/books/README.md"]],
  ["v-026cd11f","/growth/career-thinking/",{"y":"a","t":"职业思考"},["/growth/career-thinking/README.md"]],
  ["v-6ab57ea6","/growth/courses/",{"y":"a","t":"课程记录"},["/growth/courses/README.md"]],
  ["v-9f5e9706","/growth/notes/",{"y":"a","t":"学习笔记"},["/growth/notes/README.md"]],
  ["v-07839a34","/projects/ai-knowledge-base/",{"y":"a","t":"AI 知识库"},["/projects/ai-knowledge-base/README.md"]],
  ["v-4b86cb94","/projects/mini-oms/",{"y":"a","t":"Mini OMS"},["/projects/mini-oms/README.md"]],
  ["v-4b8a6e8c","/projects/mini-wms/",{"y":"a","t":"Mini WMS"},["/projects/mini-wms/README.md"]],
  ["v-62e8bd0d","/projects/open-source/",{"y":"a","t":"开源项目"},["/projects/open-source/README.md"]],
  ["v-aa59c840","/business-system/supply-chain/",{"y":"a","t":"供应链系统总览"},["/business-system/supply-chain/README.md"]],
  ["v-1a221d9e","/md/articles/mybatis-source.html",{"y":"a","t":"MyBatis 源码深度解析","i":"database"},[":md"]],
  ["v-5abebbfa","/md/articles/spring-boot.html",{"y":"a","t":"Spring Boot 核心技术","i":"spring"},[":md"]],
  ["v-2cb38e60","/projects/tools/",{"y":"a","t":"工具"},["/projects/tools/README.md"]],
  ["v-49312a44","/md/dev-log/day01.html",{"y":"a","t":"Day01","i":"laptop-code","I":0},[":md"]],
  ["v-45c77906","/md/dev-log/day02.html",{"y":"a","t":"Day02","i":"laptop-code","I":0},[":md"]],
  ["v-425dc7c8","/md/dev-log/day03.html",{"y":"a","t":"Day03","i":"laptop-code","I":0},[":md"]],
  ["v-3ef4168a","/md/dev-log/day04.html",{"y":"a","t":"Day04","i":"laptop-code","I":0},[":md"]],
  ["v-3b8a654c","/md/dev-log/day05.html",{"y":"a","t":"Day05","i":"laptop-code","I":0},[":md"]],
  ["v-3820b40e","/md/dev-log/day06.html",{"y":"a","t":"Day06","i":"laptop-code","I":0},[":md"]],
  ["v-649fe232","/md/dev-log/day07~day08.html",{"y":"a","t":"Day07 ~ Day08","i":"laptop-code","I":0},[":md"]],
  ["v-c97ab98e","/md/dev-log/day09~day10.html",{"y":"a","t":"Day09 ~ Day10","i":"laptop-code","I":0},[":md"]],
  ["v-104da61f","/md/dev-log/day11.html",{"y":"a","t":"Day011","i":"laptop-code","I":0},[":md"]],
  ["v-12027ebe","/md/dev-log/day12.html",{"y":"a","t":"Day012","i":"laptop-code","I":0},[":md"]],
  ["v-7c27fd02","/md/dev-log/",{"y":"a","t":"开发日志","i":"laptop-code"},["/md/dev-log/README.md"]],
  ["v-476ae7b4","/md/projects/lottery.html",{"y":"a","t":"Lottery 抽奖系统","i":"gift"},[":md"]],
  ["v-5dfe20a2","/growth/roadmap/",{"y":"a","t":"学习路线"},["/growth/roadmap/README.md"]],
  ["v-0c86374e","/ai/ai-coding/",{"y":"a","t":"AI Coding"},["/ai/ai-coding/README.md"]],
  ["v-66f86789","/ai/enterprise-ai/",{"y":"a","t":"企业 AI"},["/ai/enterprise-ai/README.md"]],
  ["v-e20a9876","/ai/ai-architecture/",{"y":"a","t":"AI 辅助架构设计"},["/ai/ai-architecture/README.md"]],
  ["v-44118717","/ai/prompt-engineering/",{"y":"a","t":"Prompt 工程"},["/ai/prompt-engineering/README.md"]],
  ["v-67f442f4","/ai/my-ai-tools/",{"y":"a","t":"我的 AI 工具"},["/ai/my-ai-tools/README.md"]],
  ["v-dbf7b5e2","/tech/docker/",{"y":"a","t":"Docker"},["/tech/docker/README.md"]],
  ["v-0031294d","/tech/java/",{"y":"a","t":"Java"},["/tech/java/README.md"]],
  ["v-09cb1ebb","/tech/linux/",{"y":"a","t":"Linux"},["/tech/linux/README.md"]],
  ["v-7646f60b","/tech/mq/",{"y":"a","t":"消息队列"},["/tech/mq/README.md"]],
  ["v-642e55bc","/tech/mybatis/",{"y":"a","t":"MyBatis"},["/tech/mybatis/README.md"]],
  ["v-0c63a4cd","/tech/mysql/",{"y":"a","t":"MySQL"},["/tech/mysql/README.md"]],
  ["v-13cb1b14","/tech/redis/",{"y":"a","t":"Redis"},["/tech/redis/README.md"]],
  ["v-28a178ff","/troubleshooting/java/",{"y":"a","t":"Java 问题"},["/troubleshooting/java/README.md"]],
  ["v-2136756e","/troubleshooting/linux/",{"y":"a","t":"Linux 问题"},["/troubleshooting/linux/README.md"]],
  ["v-1c05694a","/troubleshooting/mysql/",{"y":"a","t":"MySQL 问题"},["/troubleshooting/mysql/README.md"]],
  ["v-a06f9062","/troubleshooting/network/",{"y":"a","t":"网络问题"},["/troubleshooting/network/README.md"]],
  ["v-5482b090","/tech/springboot/",{"y":"a","t":"Spring Boot"},["/tech/springboot/README.md"]],
  ["v-1a46e9e6","/troubleshooting/performance/",{"y":"a","t":"性能问题"},["/troubleshooting/performance/README.md"]],
  ["v-0f75b7c8","/troubleshooting/production/",{"y":"a","t":"生产问题"},["/troubleshooting/production/README.md"]],
  ["v-cee81a28","/business-system/supply-chain/future/",{"y":"a","t":"后续扩展"},["/business-system/supply-chain/future/README.md"]],
  ["v-5df0c298","/business-system/supply-chain/oms/design-thinking.html",{"y":"a","t":"OMS 设计思考"},[":md"]],
  ["v-0b75ecc4","/business-system/supply-chain/oms/exception.html",{"y":"a","t":"异常中心"},[":md"]],
  ["v-3390be15","/business-system/supply-chain/oms/fulfillment.html",{"y":"a","t":"履约中心"},[":md"]],
  ["v-345f3699","/business-system/supply-chain/oms/inventory-center.html",{"y":"a","t":"库存中心"},[":md"]],
  ["v-5ba32c8b","/business-system/supply-chain/oms/order-center.html",{"y":"a","t":"订单中心"},[":md"]],
  ["v-db536f4c","/business-system/supply-chain/oms/",{"y":"a","t":"OMS 总览"},["/business-system/supply-chain/oms/README.md"]],
  ["v-9dd7d4a8","/business-system/supply-chain/wms/design-thinking.html",{"y":"a","t":"WMS 设计思考"},[":md"]],
  ["v-53e96952","/business-system/supply-chain/wms/inbound.html",{"y":"a","t":"入库"},[":md"]],
  ["v-30b954cf","/business-system/supply-chain/wms/inventory.html",{"y":"a","t":"仓库库存"},[":md"]],
  ["v-63f39452","/business-system/supply-chain/wms/outbound.html",{"y":"a","t":"出库"},[":md"]],
  ["v-db4c295c","/business-system/supply-chain/wms/",{"y":"a","t":"WMS 总览"},["/business-system/supply-chain/wms/README.md"]],
  ["v-e5ed677e","/business-system/supply-chain/wms/warehouse-rule.html",{"y":"a","t":"仓储规则"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-2d0aa3df","/md/",{"y":"p","t":"Md"},[]],
  ["v-e2e086da","/md/articles/",{"y":"p","t":"Articles"},[]],
  ["v-37e03df6","/md/projects/",{"y":"p","t":"Projects"},[]],
]
